import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.sql.*;
import java.text.SimpleDateFormat;

/**
 *
 * @author Home PC
 */
public class EditKid extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */

    Connection conn;
    public EditKid(Connection conn) {
        this.conn = conn;
        getContentPane().setBackground(Color.lightGray);

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLabel a3 = new JLabel("Classroom ");
        a3.setFont(new Font("Dialog",Font.BOLD,13));
        a3.setBounds(275,10,400,50);
        add(a3);

        JTextField classroom = new JTextField();
        classroom.setBounds(370,28,98,20);
        add(classroom);

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        okButton = new javax.swing.JButton();
        name = new javax.swing.JTextField();
        lastname = new javax.swing.JTextField();
        birthdate = new javax.swing.JTextField();
        breakfast = new javax.swing.JTextField();
        lunch = new javax.swing.JTextField();
        gender = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();



        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Name");

        jLabel2.setText("Surname");

        jLabel3.setText("Birhdate");

        jLabel4.setText("Gender");

        jLabel5.setText("Breakfast");

        jLabel6.setText("Lunch");

        jList1.setModel(new javax.swing.AbstractListModel<>() {
            String[] strings = {"Item 1", "Item 2", "Item 3", "Item 4", "Item 5"};

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jScrollPane1.setViewportView(jList1);

        okButton.setText("OK");

        name.setText("                               ");

        lastname.setText("                               ");

        birthdate.setText("                               ");

        breakfast.setText("                               ");

        lunch.setText("                               ");

        gender.setText("                               ");

        jLabel7.setText("Edit Student");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(65, 65, 65)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(35, 35, 35)
                                    .addComponent(lunch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(35, 35, 35)
                                    .addComponent(breakfast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(35, 35, 35)
                                .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(okButton))
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(breakfast, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(lastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lunch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(okButton)
                    .addComponent(birthdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setVisible(true);

        DefaultListModel model = new DefaultListModel();
        try{
            ResultSet kids = Kid.getAllKids(conn);
            while(kids.next()){
                model.addElement(kids.getInt("kidid") +"   "  + kids.getString("firstName") + " " +  kids.getString("lastname"));
            }
        }
        catch (Exception e){
            e.printStackTrace();
        }
        jList1.setModel(model);


        MouseListener mouseListener = new MouseAdapter() {
            public void mouseClicked(MouseEvent e) {
                if (e.getClickCount() == 2) {

                    try{
                        String selectedItem = (String) jList1.getSelectedValue();
                        String[] parts = selectedItem.split(" ");
                        int kidid = Integer.parseInt(parts[0]);
                        ResultSet info = Kid.getKidInfo(conn, kidid);
                        info.next();

                        name.setText(info.getString("firstName"));
                        lastname.setText(info.getString("lastName"));
                        birthdate.setText(info.getString("birthdate"));
                        breakfast.setText(info.getString("breakfast"));
                        lunch.setText(info.getString("lunch"));
                        gender.setText(info.getString("gender"));
                        classroom.setText(info.getString("classroom"));

                    }
                    catch (Exception ex){
                        ex.printStackTrace();
                    }

                }
            }
        };
        jList1.addMouseListener(mouseListener);


        //pop up window when ok button is clicked
        okButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String empty = "                               ";
                if(name.getText().contains(empty) || lastname.getText().contains(empty) || birthdate.getText().contains(empty) ||
                        gender.getText().contains(empty) || breakfast.getText().contains(empty) || lunch.getText().contains(empty))
                    JOptionPane.showMessageDialog(null, "All areas must be filled!");
                else {
                    try{
                        PreparedStatement statement = conn.prepareStatement("UPDATE kid SET firstName = ?, lastName = ?, birthdate = ?, breakfast = ?, lunch = ?, gender = ? ,classroom = ? WHERE kidid = ?");
                        int kidid = Integer.parseInt(jList1.getSelectedValue().split(" ")[0]);
                        statement.setString(1, name.getText());
                        statement.setString(2, lastname.getText());

                        //convert date to sql date
                        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
                        java.util.Date date = sdf1.parse(birthdate.getText());
                        java.sql.Date sqlStartDate = new java.sql.Date(date.getTime());
                        statement.setDate(3, sqlStartDate);

                        statement.setBoolean(4, breakfast.getText().equals("t"));

                        statement.setBoolean(5, lunch.getText().equals("t"));




                        statement.setString(6, gender.getText());

                        statement.setString(7, classroom.getText());

                        statement.setInt(8, kidid);
                        statement.execute();
                    }
                    catch (Exception ex){
                        ex.printStackTrace();
                        JOptionPane.showMessageDialog(null, "Check your input!");
                    }
                }
            }
        });


        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                new OgrenciIslemleri(conn);
            }
        });



    }
    // </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton okButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JTextField lastname;
    private javax.swing.JTextField birthdate;
    private javax.swing.JTextField breakfast;
    private javax.swing.JTextField lunch;
    private javax.swing.JTextField gender;
    // End of variables declaration//GEN-END:variables
}
